### ISSUE TITLE
Clearart and clearlogo

### ISSUE THREAD

**Issue by wsx79** [Angelinas1/script.artwork.downloader#2]
Clearart and clearlogo are downloaded only in English perhaps I select another language (Italian) in settings.
Poster are downloaded correctly.

**Comment by Angelinas1** [comment]
Just try it for Portuguse....working OK
![screenshot00130](https://user-images.githubusercontent.com/7657140/118140814-036b4880-b409-11eb-8023-813385a93040.png)

![New Bitmap Image](https://user-images.githubusercontent.com/7657140/118141062-46c5b700-b409-11eb-8d9e-7b9b922c41e4.jpg)

**Comment by wsx79** [comment]
I can see it in Italian Language. Where is the path of download?

**Comment by Angelinas1** [comment]
Path for download is in your local folder ... need to set in settings Local"on"and Italian  for prefered Language
![screenshot00132](https://user-images.githubusercontent.com/7657140/118366160-dc934a80-b59f-11eb-8df9-9a677b401651.png)
