### ISSUE TITLE
Issue, starting scripts results in an error

### ISSUE THREAD

**Issue by beatmasterRS** [Angelinas1/script.artwork.downloader#3]
Unfortunately I get an error as soon as I start the script. Could you have a look please? 

https://paste.kodi.tv/ewurubotev.kodi

I am using Windows 10 / Kodi19.1

Thanks a lot :)

**Comment by Angelinas1** [comment]
can you try fix for Char..
https://github.com/Angelinas1/script.artwork.downloader/commit/faf810161249c749639bdf35b4c0bbdb9d147ef5

**Comment by beatmasterRS** [comment]
Also an error:

https://paste.kodi.tv/awocopawev.kodi

**Comment by Angelinas1** [comment]
Second atempt :)
https://github.com/Angelinas1/script.artwork.downloader/commit/233b72ccbc90b78f3aa8877e971619e01ba331d5

**Comment by beatmasterRS** [comment]
Thanks, works like a charm :) 

Except the gui mode, when i call the script via:

`<onclick condition="String.IsEqual(ListItem.DBType,movie)">RunScript(script.artwork.downloader, mode=gui, mediatype=movie, medianame=$INFO[ListItem.Title])</onclick>` 

By the way i dont know, if this is the right way to call the script for a single item...

The behavior is strange: I select posters, it shows posters for the first movie in the DB, no matter, which movie i had selected. I select "back", click on "posters" and posters for the 2nd movie in DB are displayed. This goes until movie 5, then I can end the script by "back". If i want to choose a Poster, i get an error.

If you need debug logs, let me know :) 

But so far it works already :)

**Comment by Angelinas1** [comment]
@beatmasterRS 
No need to write code in skin...for solo or gui.
From DialogContextMenu chose "manage..."
![screenshot00140](https://user-images.githubusercontent.com/7657140/120094762-9fdc5d00-c122-11eb-9a97-f3f135e70189.png)

If you want to use comand ifrom other dialog use from her (old code but work )
https://github.com/Angelinas1/Aeonmq6-Leia/blob/master/1080i/DialogContextMenu.xml#L122

Better to use dbid=$INFO[ListItem.DBID]
insted of medianame=$INFO[ListItem.Title]

**Comment by beatmasterRS** [comment]
Calling the script via:

`<onclick condition="String.IsEqual(ListItem.DBType,movie)">RunScript(script.artwork.downloader, mediatype=movie, dbid=$INFO[ListItem.DBID])</onclick>`

works fine, thanks a lot :)
